name: deploy

on:
  push:
    branches:
      - production

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
         sudo apt-get install libsdl2-2.0-0
         python -m pip install --upgrade pip setuptools wheel
         python -m pip install PyInstaller
         python -m pip install PyYAML
         python -m pip install requests
         python -m pip install packaging
         python -m pip install appdirs
         python -m pip install "https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.1.1-cp38-cp38-linux_x86_64.whl"
      - name: Compile using pyinstaller
        run: |
         pyinstaller rva_points.py -w --onefile --workpath dist/linux/build --distpath ./dist/linux
         mv ./dist/linux/rva_points .
      - name: Prepare release
        uses: papeloto/action-zip@v1
        with:
          files: rva_points icons
          dest: rva_points_linux.zip
          recursive: false
      - name: Prepare FTP directories
        run: |
         mv rva_points ./dist/linux
         mv rva_points_linux.zip ./dist/linux
         rm -r ./dist/linux/build
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: rva
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./dist/linux/"
          server-dir: "rva_points/linux/"
  win64:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip setuptools wheel
         python -m pip install PyInstaller==4.4
         python -m pip install PyYAML
         python -m pip install requests
         python -m pip install packaging
         python -m pip install appdirs
         python -m pip install wxPython
      - name: Compile using pyinstaller
        run: |
         pyinstaller ./dist/rva_points.spec -w --onefile --workpath dist/win64/build --distpath ./dist/win64
         mv ./dist/win64/rva_points.exe .
      - name: Prepare release
        uses: papeloto/action-zip@v1
        with:
          files: rva_points.exe icons
          dest: rva_points_win64.zip
          recursive: false
      - name: Prepare FTP directories
        run: |
          mv rva_points.exe ./dist/win64
          mv rva_points_win64.zip ./dist/win64
          rm -r ./dist/win64/build
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./dist/win64/"
          server-dir: "rva_points/win64/"
  version:
    needs: [linux, win64]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip setuptools wheel
         python -m pip install requests
         python -m pip install packaging
         python -m pip install appdirs
      - name: Perpare rva_points.json
        run: |
         cd dist && python release.py
         mkdir version && mv rva_points.json version
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: rva
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./dist/version/"
          server-dir: "rva_points/"
